name: Update Random Meme

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # allows manual trigger
  schedule:
    - cron: '0 * * * *' # runs every hour, change as needed

jobs:
  update-meme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Fetch random meme URL from meme-api
      - name: Fetch Random Meme URL
        id: meme
        run: |
          MEME_URL=$(curl -s https://meme-api.com/gimme/ProgrammerHumor | jq -r '.url')
          echo "MEME_URL=$MEME_URL" >> $GITHUB_ENV

      # Update README.md with the new meme
      - name: Update README
        run: |
          sed -i "s|!\[Random Meme\](.*)|![Random Meme]($MEME_URL)|" README.md

      # Commit and push changes
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update random meme" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
